### ISSUE TITLE
Please implement seconds formatting

### ISSUE THREAD

**Issue by SergKam** [thaterikperson/elm-strftime#1]
Please implement seconds formatting.
%S	Second as a zero-padded decimal number.	05
%-S	Second as a decimal number. (Platform specific)	5

It's very useful for many technical applications like (logs viewer or files listers)

**Comment by arcmode** [comment]
Hi @SergKam. You can try this [branch](https://github.com/drojas/elm-strftime/tree/second-formatting) of my fork of this project that includes seconds formatting. It was super easy to implement actually. Making a PR now.

**Comment by thaterikperson** [comment]
@drojas that branch looks great. I'd be happy to merge it and republish if you create a PR.

**Comment by thaterikperson** [comment]
Thanks everyone! Fix is available: http://package.elm-lang.org/packages/thaterikperson/elm-strftime/1.0.2
